version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run: python --version
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3 -m pytest tests/step_defs/steps.py --junitxml=test-reports/report.xml
      - store_test_results:
          path: test-reports/
      - store_artifacts:
          path: test-reports/